name: Build

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: windows-latest
    name: Testing
    strategy:
      matrix:
        include: 
          - framework: "net6.0"
            version: 6.0.x
          - framework: net8.0
            version: 8.0.x
      
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
 
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.version }}
      
      - name: Run tests
        run: dotnet test --verbosity normal -f ${{ matrix.framework }}

  build:
    runs-on: windows-latest
    name: Building
    strategy:
      matrix: 
        include: 
          - framework: "net6.0"
            version: 6.0.x
          - framework: net8.0
            version: 8.0.x
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Cleaning
        run: dotnet clean

      - name: Restore NuGet packages
        run: dotnet restore WorkflowEngine.sln

      - name: Build solution
        run: dotnet build -o ../build/${{ matrix.dotnet }} -c Release --no-restore -m:1 -f  ${{ matrix.framework }}

      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/${{ matrix.framework }}/*
          retention-days: 5
